# Generated by Django 6.0.1 on 2026-02-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'MY Products'},
        ),
    ]
