# Generated by Django 6.0.1 on 2026-02-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
