# Generated by Django 6.0.1 on 2026-02-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='female',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Female Name'),
        ),
        migrations.AlterField(
            model_name='male',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Male Name'),
        ),
    ]
