# Generated by Django 6.0.1 on 2026-02-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='product name', max_length=50),
        ),
    ]
