# Generated by Django 6.0.1 on 2026-02-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_products_user_product_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(null=True, to='pages.product'),
        ),
    ]
