# Generated by Django 6.0.1 on 2026-02-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='LoginData',
        ),
    ]
