# Generated by Django 6.0.1 on 2026-02-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_login_logindata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
